### PR TITLE
Conflicting protein commit; closes #1

### LINKED ISSUE #1: Proposal for more protein
While the initial recipe looks nice it is missing some protein for a balanced, healthy meal.

### PR DESCRIPTION
**Pull request by Phency**
Hope this will create a conflict, but uncertain

### CODE REVIEW

**Comment by bast** [comment]
Let's see once we start merging.

**Comment by bast** [comment]
No conflict. Was the filename the same?

**Comment by Phency** [comment]
No it was a different file name. I guess that is where the problem is.

**Comment by bast** [comment]
What was the other pull request that this was expected to conflict with? I can then check why it didn't.

**Comment by Phency** [comment]
Add protein into coderefinery tacos; closes #1

**Comment by bast** [comment]
To get a conflict we would need two pull requests that both modify the same file (portions) in two different ways.

**Comment by bast** [comment]
Now we have a conflict! Nice! You can try to resolve it directly here in the browser.

**Comment by bast** [comment]
Awesome.

**Pull request merged**
